export default {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_ITEM_IN_CART: "ADD_ITEM_IN_CART",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
};
